config/routes.rb
Rails.application.routes.draw do
  resources :movie_characters
  resources :movie_actors
  resources :characters
  resources :actors
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord

    has_many :movie_actors
    has_many :movies, through: :movie_actors
    has_many :characters
    

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord

    has_many :movie_characters
    has_many :movies, through: :movie_characters
    belongs_to :actor

    
end

app/models/movie.rb
class Movie < ApplicationRecord

    has_many :movie_actors
    has_many :actors, through: :movie_actors
    has_many :movie_characters
    has_many :characters, through: :movie_characters

    validates :title, presence: true
    validates :release_year, presence: true
    validates :synopsis, length: {in: 50..500}

    def self.search_by(search_term)
        where("LOWER(name) LIKE :search_term", search_term: "#{search_term}")
    end

end

app/models/movie_actor.rb
class MovieActor < ApplicationRecord
    
    belongs_to :actor
    belongs_to :movie
end

app/models/movie_character.rb
class MovieCharacter < ApplicationRecord

    belongs_to :character
    belongs_to :movie
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]


  def index
    @actors = Actor.all
  end

 
  def show
    set_actor
  end


  def new
    @actor = Actor.new
  end

  def edit
    set_actor
  end

  def create
   @actor = Actor.new(actor_params)
    @actor.save
    redirect_to actor_path(@actor)
  end

 
  def update
    @actor = Actor.find(params[:id])
    @actor.update(actor_params)
    redirect_to actor_path(@actor)
  end

  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy
    redirect_to actors_path
  end

  private
    
    def set_actor
      @actor = Actor.find(params[:id])
    end

    def actor_params
      params.require(:actor).permit(:name, :gender, :age)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  def index
    @characters = Character.all
  end

  def show
    set_character
  end

  def new
    @character = Character.new
  end


  def edit
    set_character
  end

  
  def create
    @character = Character.new(character_params)
    @character.save
    redirect_to character_path(@character)
  end

  def update
    @character = Character.find(params[:id])
    @character.update(character_params)
    redirect_to character_path(@character)
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy
    redirect_to characters_path
  end

  private
   
    def set_character
      @character = Character.find(params[:id])
    end

    def character_params
      params.require(:character).permit(:name, :gender, :profession, :actor_id)
    end
end

app/controllers/movie_actors_controller.rb
class MovieActorsController < ApplicationController
  before_action :set_movie_actor, only: [:show, :edit, :update, :destroy]

  def index
    @movie_actors = MovieActor.all
  end

  private

    def set_movie_actor
      @movie_actor = MovieActor.find(params[:id])
    end

  
    def movie_actor_params
      params.require(:movie_actor).permit(:movie_id, :actor_id)
    end
end

app/controllers/movie_characters_controller.rb
class MovieCharactersController < ApplicationController
  before_action :set_movie_character, only: [:show, :edit, :update, :destroy]

  def index
    @movie_characters = MovieCharacter.all
  end

 
  private
   
    def set_movie_character
      @movie_character = MovieCharacter.find(params[:id])
    end


    def movie_character_params
      params.require(:movie_character).permit(:movie_id, :character_id)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

 

  def index
    @movies = Movie.all
    if params[:search]
      @search_term = params[:search]
      @movies = @movies.search_by(@search_term)
    end
  end

  def show
    set_movie
  end


  def new
    @movie = Movie.new
  end

 
  def edit
  end


  def create
    @movie = Movie.new(movie_params)
    @movie.save
    redirect_to movie_path(@movie)
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(movie_params)
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  private
 
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :genre, :synopsis, :release_year, :search)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/movie_actors_helper.rb
module MovieActorsHelper
end

app/helpers/movie_characters_helper.rb
module MovieCharactersHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/actors/_form.html.erb
<%= form_with(model: actor, local: true) do |form| %>
  <% if actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
        <% actor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing Actor</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Actors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <%= link_to 'Add New Actor', new_actor_path %>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
      <td><%= link_to actor.name, actor_path(actor) %></td>
        <td><%= actor.gender %></td>
        <td><%= actor.age %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= button_to 'Delete', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/actors/new.html.erb
<h1>New Actor</h1>

<%= render 'form', actor: @actor %>
<%= f.collection_select :actor_id, Actor.all, :id, :name %>


<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @actor.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @actor.gender %>
</p>

<p>
  <strong>Age:</strong>
  <%= @actor.age %>
</p>

<p>  
<ul>
<strong> Character: </strong>
<% @actor.characters.each do |character| %>
<li> <%= link_to character.name, character_path(character) %> </li>
<%end %>
</ul>
</p>

<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>

app/views/characters/_form.html.erb
<%= form_with(model: character, local: true) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
        <% character.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :profession %>
    <%= form.text_field :profession %>
  </div>
  
  <%= form.collection_select :actor_id, Actor.all, :id, :name %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing Character</h1>

<%= render 'form', character: @character %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Characters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Profession</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <%= link_to 'Add New Character', new_actor_path %>

  <tbody>
    <% @characters.each do |character| %>
      <tr>
        <td><%= link_to character.name, character_path(character) %></td>
        <td><%= character.gender %></td>
        <td><%= character.profession %></td>
        <td><%= link_to 'Edit', edit_character_path(character) %></td>
        <td><%= button_to 'Delete', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/characters/new.html.erb
<h1>New Character</h1>

<%= render 'form', character: @character %>
<%= form_for @character do |f| %>

    
<% end %>
<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @character.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @character.gender %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @character.profession %>
</p>

<p> 
<ul>
<strong> Movie(s) this character is in: </strong>
<% @character.movies.each do |movie| %>
<li><%=  link_to movie.title, movie_path(movie) %></li>
<%end %>
</ul>
</p>

<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mod2Project</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <section class="section">
  <div class="content">
    <%= yield %>
  </div>
</section>
  </body>
</html>

app/views/movie_actors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movie Actors</h1>

<table>
  <thead>
    <tr>
      <th>Movie</th>
      <th>Actor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_actors.each do |movie_actor| %>
      <tr>
        <td><%= movie_actor.movie_id %></td>
        <td><%= movie_actor.actor_id %></td>
        <td><%= link_to 'Show', movie_actor %></td>
        <td><%= link_to 'Edit', edit_movie_actor_path(movie_actor) %></td>
        <td><%= link_to 'Destroy', movie_actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie Actor', new_movie_actor_path %>

app/views/movie_characters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movie Characters</h1>

<table>
  <thead>
    <tr>
      <th>Movie</th>
      <th>Character</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_characters.each do |movie_character| %>
      <tr>
        <td><%= movie_character.movie_id %></td>
        <td><%= movie_character.character_id %></td>
        <td><%= link_to 'Show', movie_character %></td>
        <td><%= link_to 'Edit', edit_movie_character_path(movie_character) %></td>
        <td><%= link_to 'Destroy', movie_character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie Character', new_movie_character_path %>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :synopsis %>
    <%= form.text_field :synopsis %>
  </div>

  <div class="field">
    <%= form.label :release_year %>
    <%= form.number_field :release_year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<%= form_for "", url: movies_path, role: "search", method: :get do %>
  <%text_field_tag :search, @search_term, placeholder: "Search..." %>
  <% end %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Synopsis</th>
      <th>Release year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <%= link_to 'Add New Movie', new_movie_path %>
 
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.title, movie_path(movie) %></td>
        <td><%= movie.genre %></td>
        <td><%= movie.synopsis %></td>
        <td><%= movie.release_year %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= button_to  'Delete', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @movie.genre %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @movie.synopsis %>
</p>

<p>
  <strong>Release year:</strong>
  <%= @movie.release_year %>
</p>

<p> 
<strong> Actors: </strong>

<%  @movie.actors.each do |actor| %>
<ul>
<li><%= link_to actor.name, actor_path(actor) %>
</ul>
<% end %>
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>